### ISSUE TITLE
Нечитабельный код (hard-code)

### ISSUE THREAD

**Issue by ivanvikvik** [nikishkaa/Stage11#1]
https://github.com/nikishkaa/Stage11/blob/86c37f02902235f2c5ededd95801e59bdf1d11cd/src/by/itsteap/goutor/javatask/stage11/task/alldivisor/model/AllDivisorsLogic.java#L10
Откуда взялось число 10?
И почему делителей максимум может быть 10?

**Comment by nikishkaa** [comment]
Update task allDivisor. New name classes. Update logic efficiency. Now logic return StringBuilder. Delete unnecessary class.

**Comment by nikishkaa** [comment]
Update task all divisor.
