### ISSUE TITLE
Непроизводительный код

### ISSUE THREAD

**Issue by ivanvikvik** [nikishkaa/Stage11#3]
https://github.com/nikishkaa/Stage11/blob/86c37f02902235f2c5ededd95801e59bdf1d11cd/src/by/itsteap/goutor/javatask/stage11/task/allprimedivisors/model/PrimeDivisorsLogic.java#L14
Вычисление корня квадратного можно было вынести за пределы цикла.

**Comment by nikishkaa** [comment]
Calculating the square root outside the loop.
