### ISSUE TITLE
Нечитабельный код (hard-code)

### ISSUE THREAD

**Issue by ivanvikvik** [nikishkaa/Stage11#4]
https://github.com/nikishkaa/Stage11/blob/86c37f02902235f2c5ededd95801e59bdf1d11cd/src/by/itsteap/goutor/javatask/stage11/task/allprimedivisors/model/PrimeDivisorsLogic.java#L10
Почему создаётся массив на десять элементов?

**Comment by nikishkaa** [comment]
Class NumberLogic now return StringBuilder.
